import assert from 'node:assert/strict';
import { extractSitemapEntry, renderSitemap } from '../src/lib/sitemap-content.ts';
const origin = 'https://werigo.co';
const html = (url, extra = '', body = '') => `<html><head><link href="${url}" rel="canonical">${extra}</head><body>${body}</body></html>`;
const extract = (url, extra = '', body = '', status = 200) => extractSitemapEntry(url, html(url,extra,body), origin,status);
assert.equal(extract('/terms','<meta name="robots" content="noindex, follow">'),null);
assert.equal(extract('/private','<meta content="none" name="googlebot">'),null);
assert.equal(extract('/old','<meta http-equiv="refresh" content="0;url=/fleet">'),null);
for (const url of ['/admin','/api/bookings','/_not-found','/book/checkout','/book/confirmation','/fleet?utm_source=x','/saga#chapters']) assert.equal(extract(url),null);
for (const status of [301,307,308,404,500,503]) assert.equal(extract('/fleet','','',status),null);
assert.equal(extractSitemapEntry('/duplicate',html('/fleet'),origin),null);
assert.equal(extractSitemapEntry('/fleet',html('https://other.test/fleet'),origin),null);
assert.equal(extractSitemapEntry('/fleet','<html><head></head></html>',origin),null);
assert.equal(extractSitemapEntry('/',html(origin),origin).url,origin);
assert.equal(extract('/fleet').lastModified,undefined);
assert.equal(extract('/fleet','<meta property="article:modified_time" content="2026-09-30T10:00:00Z">').lastModified,'2026-09-30T10:00:00Z');
assert.equal(extract('/fleet','<meta property="article:modified_time" content="garbage">').lastModified,undefined);
assert.equal(extract('/fleet','<meta property="article:modified_time" content="2999-01-01">').lastModified,undefined);
const newChapter=extract('/saga/chapter-21');
assert.equal(newChapter.group,'saga');
assert.equal(extract('/fleet/new-model').group,'fleet');
assert.equal(extract('/delivery-areas/new-area').group,'location');
assert.equal(extract('/new-landing').group,'page');
const e = extract('/fleet/bees','',`<img alt="Bees" src="/_next/image?url=%2Fmedia%2Ffleet%2Fbees%2Fcatalog.webp%3Fv%3D2%26x%3D1&amp;w=640"><img alt="logo" src="/brand/logo.png"><img alt="" src="/media/decorative.webp"><img alt="external" src="https://other.test/media/a.webp"><img aria-hidden="true" alt="hidden" src="/media/hidden.webp">`);
assert.deepEqual(e.images,['https://werigo.co/media/fleet/bees/catalog.webp?v=2&x=1']);
assert.match(renderSitemap('image',[e],origin),/v=2&amp;x=1/);
assert.equal((renderSitemap('index',[],origin).match(/<sitemap>/g)||[]).length,5);
assert.match(renderSitemap('saga',[newChapter],origin),/chapter-21/);
assert.doesNotMatch(renderSitemap('fleet',[newChapter],origin),/chapter-21/);
assert.throws(()=>renderSitemap('fleet',Array(50001).fill(e),origin),/50,000/);
console.log('PASS: publication/status/noindex/canonical filters, new content discovery, dates, image filtering, XML escaping and sitemap limits.');
